export const SET_AUTH = 'SET_AUTH';
export const SET_CUR_USER = 'SET_CUR_USER';
export const SET_CUR_RECORD = 'SET_CUR_RECORD';
export const SET_CUR_USER_NAME = 'SET_CUR_USER_NAME';
export const SET_CUR_USER_SERIAL = 'SET_CUR_USER_SERIAL';
export const SET_COUNTDOWN_VALUE = 'SET_COUNTDOWN_VALUE';
